## Intoduction to Tensorflow

In [36]:
!pip install tensorflow


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [37]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__,'Installed successfully!')

TensorFlow version: 2.20.0 Installed successfully!


In [38]:
# create a constant tensor
scalar = tf.constant(42)
print("Scalar tensor:", scalar)

Scalar tensor: tf.Tensor(42, shape=(), dtype=int32)


In [39]:
# check the no of dimensions (ndims)
print("Number of dimensions:", scalar.ndim)

Number of dimensions: 0


In [40]:
# create a 1-D tensor (vector)
vector = tf.constant([1, 2, 3, 4, 5])
print("Vector tensor:", vector)
print("Number of dimensions:", vector.ndim)

Vector tensor: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Number of dimensions: 1


In [41]:
# create a matrix (2-D tensor)
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Matrix tensor:\n", matrix)
print("Number of dimensions:", matrix.ndim)

Matrix tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Number of dimensions: 2


In [42]:
#  create another 3-D tensor
another_matrix = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=tf.float16)
print("Another Matrix tensor:\n", another_matrix)  
print("Number of dimensions:", another_matrix.ndim) 

Another Matrix tensor:
 tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float16)
Number of dimensions: 3


In [66]:
# create the same tensor with tf.Variable
variable_tensor = tf.Variable([[1, 2, 3],[4, 5, 6]])
print("Variable tensor:\n", variable_tensor)    


Variable tensor:
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


# Create random tensors with tf.random.Generator

In [67]:
# create random tensor
random_tensor = tf.random.uniform(shape=(3, 4), minval=0, maxval=10)
print("Random tensor:\n", random_tensor)    

Random tensor:
 tf.Tensor(
[[6.6456213  4.4100676  3.528825   4.6448255 ]
 [0.33660412 6.8467236  7.4011745  8.724445  ]
 [2.2632635  2.2319686  3.103881   7.223358  ]], shape=(3, 4), dtype=float32)


In [68]:
# Create Two random (but the same) tensors
random_tensor_1 = tf.random.Generator.from_seed(42).normal(shape=(3, 4))
random_tensor_2 = tf.random.Generator.from_seed(42).normal(shape=(3, 4))
print("Random tensor 1:\n", random_tensor_1)
print("Random tensor 2:\n", random_tensor_2)
random_tensor_1 == random_tensor_2

Random tensor 1:
 tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855   0.09988727 -0.50998646]
 [-0.7535805  -0.57166284  0.1480774  -0.23362993]], shape=(3, 4), dtype=float32)
Random tensor 2:
 tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855   0.09988727 -0.50998646]
 [-0.7535805  -0.57166284  0.1480774  -0.23362993]], shape=(3, 4), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

## Shuffle , Reshape the order of elements in a tensor

In [69]:
# shuffle a tensor
# we do this to make sure the order of our data is random and not in a specific order (e.g. sorted)
shuffled_tensor = tf.random.shuffle(random_tensor)
print("Shuffled tensor:\n", shuffled_tensor)
# reshape a tensor
reshaped_tensor = tf.reshape(random_tensor, shape=(4, 3))
print("Reshaped tensor:\n", reshaped_tensor)
# get the min and max values of a tensor
min_value = tf.reduce_min(random_tensor)
max_value = tf.reduce_max(random_tensor)
print("Min value:", min_value.numpy())
print("Max value:", max_value.numpy())
# get the mean and sum of a tensor
mean_value = tf.reduce_mean(random_tensor)
sum_value = tf.reduce_sum(random_tensor)
print("Mean value:", mean_value.numpy())
print("Sum value:", sum_value.numpy())
# get the index of max value
argmax_index = tf.argmax(random_tensor)         
print("Index of max value:", argmax_index.numpy())

Shuffled tensor:
 tf.Tensor(
[[2.2632635  2.2319686  3.103881   7.223358  ]
 [6.6456213  4.4100676  3.528825   4.6448255 ]
 [0.33660412 6.8467236  7.4011745  8.724445  ]], shape=(3, 4), dtype=float32)
Reshaped tensor:
 tf.Tensor(
[[6.6456213  4.4100676  3.528825  ]
 [4.6448255  0.33660412 6.8467236 ]
 [7.4011745  8.724445   2.2632635 ]
 [2.2319686  3.103881   7.223358  ]], shape=(4, 3), dtype=float32)
Min value: 0.33660412
Max value: 8.724445
Mean value: 4.780063
Sum value: 57.36076
Index of max value: [0 1 1 1]


# other ways to make tensors with np.array() and tf.convert_to_tensor() 

In [70]:
# creating tensors from NumPy arrays
import numpy as np
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = tf.convert_to_tensor(numpy_array)   
print("Tensor from NumPy array:\n", tensor_from_numpy)
# converting tensors to NumPy arrays
tensor_to_convert = tf.constant([[7, 8, 9], [10, 11, 12]])
numpy_from_tensor = tensor_to_convert.numpy()   
print("NumPy array from tensor:\n", numpy_from_tensor)  


Tensor from NumPy array:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
NumPy array from tensor:
 [[ 7  8  9]
 [10 11 12]]


In [81]:
numpy_A= np.array([[1, 2], [3, 4]])
tensor_A = tf.constant(numpy_A,shape=(2, 2), dtype=tf.float32)
tensor_A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [84]:
tensor_A.numpy()
A=np.array([[1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]],)
tensor_B=tf.constant(A,shape=(2, 2, 6), dtype=tf.float32)
tensor_B

<tf.Tensor: shape=(2, 2, 6), dtype=float32, numpy=
array([[[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]],

       [[13., 14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23., 24.]]], dtype=float32)>

In [85]:
tensor_c=tf.reshape(tensor_B,shape=(4, 3, 2))
tensor_c

<tf.Tensor: shape=(4, 3, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]],

       [[19., 20.],
        [21., 22.],
        [23., 24.]]], dtype=float32)>

In [86]:
# create tensor with tf.ones() and tf.zeros()
ones_tensor = tf.ones(shape=(2, 3))
zeros_tensor = tf.zeros(shape=(2, 3))   
print("Ones tensor:\n", ones_tensor)
print("Zeros tensor:\n", zeros_tensor)

Ones tensor:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Zeros tensor:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [77]:
# global random seed and operation-level random seed
tf.random.set_seed(42)  # global seed
random_tensor_1 = tf.random.uniform(shape=(2, 2), seed=1)  # operation-level seed
random_tensor_2 = tf.random.uniform(shape=(2, 2), seed=1)  # operation-level seed
print("Random Tensor 1:\n", random_tensor_1)  
print("Random Tensor 2:\n", random_tensor_2)      

Random Tensor 1:
 tf.Tensor(
[[0.15012848 0.63992536]
 [0.81787777 0.34572172]], shape=(2, 2), dtype=float32)
Random Tensor 2:
 tf.Tensor(
[[0.8578867  0.3187294 ]
 [0.8435819  0.13991392]], shape=(2, 2), dtype=float32)


## getting information from tensors

In [89]:
# getting more info about tensors (tensor attributes)
print("Data type of random_tensor_1:", random_tensor_1.dtype)
print("Shape of random_tensor_1:", random_tensor_1.shape)   
print("Size of random_tensor_1:", tf.size(random_tensor_1).numpy())
print("Number of dimensions of random_tensor_1:", random_tensor_1.ndim) #rank
# changing data types of tensors (casting)
casted_tensor = tf.cast(random_tensor_1, dtype=tf.float32)
print("Casted tensor:\n", casted_tensor)
print("Data type of casted_tensor:", casted_tensor.dtype)
#axis or dimension
print("Shape of random_tensor_1:", random_tensor_1.shape)
print("Shape of casted_tensor:", casted_tensor.shape)


Data type of random_tensor_1: <dtype: 'float32'>
Shape of random_tensor_1: (2, 2)
Size of random_tensor_1: 4
Number of dimensions of random_tensor_1: 2
Casted tensor:
 tf.Tensor(
[[0.15012848 0.63992536]
 [0.81787777 0.34572172]], shape=(2, 2), dtype=float32)
Data type of casted_tensor: <dtype: 'float32'>
Shape of random_tensor_1: (2, 2)
Shape of casted_tensor: (2, 2)


In [73]:
# create a rank 4 tensor (4-D tensor)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
print(rank_4_tensor)
print("Rank 4 tensor shape:", rank_4_tensor.shape)
print("Number of dimensions:", rank_4_tensor.ndim)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)
Rank 4 tensor shape: (2, 3, 4, 5)
Number of dimensions: 4


In [74]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [75]:
#indexing and slicing tensors and expanding tensors
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# indexing  
print("First row:", tensor_2d[0].numpy())
print("Second column:", tensor_2d[:, 1].numpy())
# slicing
print("Sliced tensor (rows 0-1, columns 1-2):\n", tensor_2d[0:2, 1:3].numpy())
# expanding dimensions  
expanded_tensor = tf.expand_dims(tensor_2d, axis=0)
print("Expanded tensor shape:", expanded_tensor.shape)  
# squeezing dimensions
squeezed_tensor = tf.squeeze(expanded_tensor)   
print("Squeezed tensor shape:", squeezed_tensor.shape)  
# stacking tensors
tensor_a = tf.constant([1, 2, 3])
tensor_b = tf.constant([4, 5, 6])
stacked_tensor = tf.stack([tensor_a, tensor_b], axis=0)
print("Stacked tensor:\n", stacked_tensor.numpy())
# unstacking tensors    
unstacked_tensors = tf.unstack(stacked_tensor, axis=0)
print("Unstacked tensors:") 
for t in unstacked_tensors:
    print(t.numpy())        


First row: [1 2 3]
Second column: [2 5 8]
Sliced tensor (rows 0-1, columns 1-2):
 [[2 3]
 [5 6]]
Expanded tensor shape: (1, 3, 3)
Squeezed tensor shape: (3, 3)
Stacked tensor:
 [[1 2 3]
 [4 5 6]]
Unstacked tensors:
[1 2 3]
[4 5 6]


# Manipulating tensors (tensor operations)
**basic operations**
- Addition: `tf.add()`, `+`
- Subtraction: `tf.subtract()`, `-`
- Multiplication: `tf.multiply()`, `*`
- Division: `tf.divide()`, `/`  

In [90]:
tensor=tf.constant([[1, 2], [3, 4]])
print("Original tensor:\n", tensor)
# basic operations
# Addition
added_tensor = tf.add(tensor, 10)
print("Added tensor:\n", added_tensor)
# Subtraction
subtracted_tensor = tf.subtract(tensor, 2)
print("Subtracted tensor:\n", subtracted_tensor)
# Multiplication
multiplied_tensor = tf.multiply(tensor, 3)
print("Multiplied tensor:\n", multiplied_tensor)
# Division
divided_tensor = tf.divide(tensor, 2)
print("Divided tensor:\n", divided_tensor)  

Original tensor:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Added tensor:
 tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
Subtracted tensor:
 tf.Tensor(
[[-1  0]
 [ 1  2]], shape=(2, 2), dtype=int32)
Multiplied tensor:
 tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)
Divided tensor:
 tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


# performing basic arithmetic operations on tensors

In [88]:
# performing basic arithmetic operations on tensors
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])
sum_tensor = tf.add(tensor_a, tensor_b)
print("Sum of tensors:\n", sum_tensor)
diff_tensor = tf.subtract(tensor_b, tensor_a)
print("Difference of tensors:\n", diff_tensor)
prod_tensor = tf.multiply(tensor_a, tensor_b)
print("Product of tensors:\n", prod_tensor)
div_tensor = tf.divide(tensor_b, tensor_a)
print("Division of tensors:\n", div_tensor)
# matrix multiplication
matmul_tensor = tf.matmul(tensor_a, tensor_b)
print("Matrix multiplication of tensors:\n", matmul_tensor)
# using TensorFlow functions within a @tf.function for performance optimization
@tf.function
def compute_operations(x, y):
    return tf.add(x, y), tf.matmul(x, y)    
add_result, matmul_result = compute_operations(tensor_a, tensor_b)
print("Add result from tf.function:\n", add_result)     
print("Matmul result from tf.function:\n", matmul_result)

Sum of tensors:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Difference of tensors:
 tf.Tensor(
[[4 4]
 [4 4]], shape=(2, 2), dtype=int32)
Product of tensors:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Division of tensors:
 tf.Tensor(
[[5.         3.        ]
 [2.33333333 2.        ]], shape=(2, 2), dtype=float64)
Matrix multiplication of tensors:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Add result from tf.function:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Matmul result from tf.function:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## Matrics multiplication with tf.matmul() and @ operator

## Its a dot product of two tensors

In [93]:
tensor=tf.constant([[1, 2], [3, 4]])
print(tensor)
tf.matmul(tensor, tensor)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [91]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [76]:
# matrix multiplication vs element-wise multiplication
matrix_a = tf.constant([[1, 2], [3, 4]])    
matrix_b = tf.constant([[5, 6], [7, 8]])
# matrix multiplication
matmul_result = tf.matmul(matrix_a, matrix_b)
print("Matrix multiplication result:\n", matmul_result.numpy())
# element-wise multiplication
elementwise_result = tf.multiply(matrix_a, matrix_b)
print("Element-wise multiplication result:\n", elementwise_result.numpy())


Matrix multiplication result:
 [[19 22]
 [43 50]]
Element-wise multiplication result:
 [[ 5 12]
 [21 32]]


In [94]:
# transpose of a tensor
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original tensor:\n", tensor_2d)
print("Transposed tensor:\n", tf.transpose(tensor_2d))


Original tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Transposed tensor:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [95]:
tf.tensordot(tensor_a, tensor_b, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

## aggregatiing tensors 

In [96]:
# aggregatiing tensors = condensing a tensor down from multiple values to a smaller amount of values
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Original tensor:\n", tensor_3d)  
print("Sum of all elements in tensor:\n", tf.reduce_sum(tensor_3d).numpy())
print("Mean of all elements in tensor:\n", tf.reduce_mean(tensor_3d).numpy())       
print("Absolute value of -5:\n", tf.abs(-5).numpy())
print("Absolute values of tensor elements:\n", tf.abs(tensor_3d).numpy())

Original tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Sum of all elements in tensor:
 36
Mean of all elements in tensor:
 4
Absolute value of -5:
 5
Absolute values of tensor elements:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [100]:
# create a random tensor with values between 0 and 100 of size 50
random_tensor = tf.constant(np.random.randint(0, 100, size=(50)))
random_tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([52, 64,  3, 16, 11, 48, 73, 56, 84, 94, 67, 65, 72, 30, 82, 11,  4,
       29, 23, 70, 92, 18, 79, 66, 42, 63, 11, 17, 77, 81, 15, 49, 16, 60,
       24, 13, 15, 37,  6, 16, 38, 22, 92, 37, 59, 67, 87, 75, 15, 90],
      dtype=int32)>

In [101]:
# find the min and max values of the random tensor
min_value = tf.reduce_min(random_tensor)
max_value = tf.reduce_max(random_tensor)
# find mean and sum of the random tensor
mean_value = tf.reduce_mean(random_tensor)  
sum_value = tf.reduce_sum(random_tensor)
print("Min value:", min_value.numpy())
print("Max value:", max_value.numpy())  
print("Mean value:", mean_value.numpy())
print("Sum value:", sum_value.numpy())

Min value: 3
Max value: 94
Mean value: 46
Sum value: 2333


In [ ]:
# finding variance and standard deviation of a tensor
variance1 = tf.math.reduce_variance(tf.cast(random_tensor, tf.float32))
print("Variance:", variance1.numpy())
standard_deviation = tf.math.reduce_std(tf.cast(random_tensor, tf.float32))
print("Standard Deviation:", standard_deviation.numpy())

TypeError: Input must be either real or complex. Received integer type <dtype: 'int32'>.